#spring.datasource.url=jdbc:postgresql://localhost:5432/carpoolapp
#spring.datasource.username=postgres
#spring.datasource.password=postgresql6608

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/carpoolapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgresql6608}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8080

#jwt.secret=carpoolapp-super-secret-key-that-is-long-enough-for-hs256
#jwt.expiration=86400000

jwt.secret=${JWT_SECRET:carpoolapp-super-secret-key-that-is-long-enough-for-hs256}
jwt.expiration=${JWT_EXPIRATION:86400000}